spring:
  application.name: orchestrator-service
payment-service.url: ${PAYMENT_SERVICE_URL:http://localhost:8081}
concert-service.url: ${CONCERT_SERVICE_URL:http://localhost:8082}
app.demo.enabled: true
